name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Syntax check
      run: vendor/bin/php-cs-fixer fix --allow-risky=yes -v --dry-run --config=.php-cs-fixer.php --stop-on-violation
    
    - name: Run test suite
      run: vendor/bin/phpunit tests --colors --testdox
